version: "3.9"

services:
  database:
    container_name: user
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_db
    expose:
      - 5432
    network_mode: host

volumes:
  postgres_data: